services:
  postgres:
    image: postgres:17.5
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: weatherdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: logs
      CLICKHOUSE_PASSWORD: logs
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse:/var/lib/clickhouse
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "logs", "--password", "logs", "--query", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 20s
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  weather_service:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080

      API_WEATHER_KEY: 90685795f8d642e181dc95363883e296

      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: weatherdb

      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: logs
      CLICKHOUSE_PASSWORD: logs
      CLICKHOUSE_DB: logs

  smtp_service:
    build: ./smtp_service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672/
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER:
      SMTP_PASSWORD:
      SMTP_FROM: noreply@example.com

    depends_on:
      - rabbit

volumes:
  postgres:
    driver: local
  clickhouse:
    driver: local